export const TOGGLE_VERBS_LIST_VISIBILITY = 'TOGGLE_VERBS_LIST_VISIBILITY';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_NEXT_VERB = 'SET_NEXT_VERB';
export const SET_VERB = 'SET_VERB_FROM_LIST';
export const CHANGE_TYPE_VISIBILITY = 'CHANGE_TYPE_VISIBILITY';
