export const TOGGLE_VERBS_LIST_VISIBILITY = 'TOGGLE_VERBS_LIST_VISIBILITY';
export const TOGGLE_ANSWER_VISIBILITY = 'TOGGLE_ANSWER_VISIBILITY';
export const SET_CORRECT_ANSWER_FLAG = 'SET_CORRECT_ANSWER';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_TOUCHED_FLAG = 'SET_TOUCHED';
export const SET_ANSWER_VALUE = 'SET_ANSWER';
export const SET_NEXT_VERB = 'SET_NEXT_VERB';
export const SET_VERB = 'SET_VERB_FROM_LIST';
